# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1agi2J1LO_x4lt9HeORIp6NONG48kCWOt

required libraries:
"""

!pip install transformers torch streamlit

"""libraries:"""

from transformers import pipeline
import streamlit as st

"""sentiment analysis function"""

def analyze_sentiment(text):
    sentiment_pipeline = pipeline("sentiment-analysis")
    result = sentiment_pipeline(text)[0]
    return result['label'], result['score']

